### ISSUE TITLE
Feature request: use the built-in rating dialog API for uwp instead of launching the store app 

### ISSUE THREAD

**Issue by dpaulino** [FabriBertani/Plugin.XamarinAppRating#1]
The UX of launching the store app to rate UWP apps is subpar compared to launching the built-in ratings dialog. 

Full details: https://docs.microsoft.com/en-us/windows/uwp/monetize/request-ratings-and-reviews#show-a-rating-and-review-dialog-in-your-app

Example of the dialog this API launches
![image](https://user-images.githubusercontent.com/7649589/96045841-67a03c80-0e27-11eb-9ffb-310abb701bc2.png)

**Comment by FabriBertani** [comment]
Added on v1.1.0

Thanks for your suggestion!
