### ISSUE TITLE
App rating prompt not appearing on Android

### ISSUE THREAD

**Issue by Suryakomma** [FabriBertani/Plugin.XamarinAppRating#2]
I have tried using the library with a sample xamarin forms project and on android i get "There was an error launching in-app review. Please try again" pop-up. i have tried on different devices but was never able to get the rating prompt on the app. i have attached the screenshot for your reference.
![error](https://user-images.githubusercontent.com/37623812/221832563-a43ee31d-d83d-4834-92f8-f1c778081d2d.png)

here is the application output when the in-app rating method is called,

[PlayCore] UID: [10154]  PID: [10738] ReviewService : requestInAppReview (com.facebook.katana)
[PlayCore] UID: [10154]  PID: [10738] ReviewService : Initiate binding to the service.
[PlayCore] UID: [10154]  PID: [10738] ReviewService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.inappreviewservice.InAppReviewService})
[PlayCore] UID: [10154]  PID: [10738] ReviewService : linkToDeath
[PlayCore] UID: [10154]  PID: [10738] OnRequestInstallCallback : onGetLaunchReviewFlowInfo
[PlayCore] UID: [10154]  PID: [10738] ReviewService : Unbind from service.
[PlayCore] UID: [10154]  PID: [10738] ReviewService : reportBinderDeath
[PlayCore] UID: [10154]  PID: [10738] ReviewService : com.google.android.finsky.inappreviewservice.InAppReviewService : Binder has died.

tested on API 30

**Comment by FabriBertani** [comment]
Hi @Suryakomma, thanks for letting me know about this and I apologize for the late response.

I've fixed this issue and it's available on the latest version [v1.2.2](https://www.nuget.org/packages/Plugin.XamarinAppRating/1.2.2).

Also, I've created a version of this package for .Net MAUI, you can check it out [here](https://github.com/FabriBertani/Plugin.Maui.AppRating), but it's only available for Android and iOS at the moment.

Best regards.
